### ISSUE TITLE
I do not see the rockets for more planets, EGI; tier 4,5,6,7,8 rockets

### ISSUE THREAD

**Issue by beetweenlands** [SteveKunG/MorePlanets#120]
title explains it, im running newest more planets version and newest stevekunG'slib

**Comment by beetweenlands** [comment]
I do see the planets just not the advanced rockets

**Comment by LinuxSquare** [comment]
Hey there @beetweenlands 

Have you checked the Celestial-Map (default: M) and looked which tiers each planet require (Top-Centre, should be Tier x)?
(Otherwise you can check with the `/dimensiontp` of GC)

I'm having a similar question, (see #117) where the planets only require a tier 3 rocket to travel to them.
Does your installation require as well only tier 3? (Just wondering if I'm the only one with this problem)

Thank you in advance.

Kind regards
LinuxSquare

**Comment by dogcat1247** [comment]
I do see the planets now, however I don't see any new rockets or the ion cannon

**Comment by ROMVoid95** [comment]
The rockets from MorePlanets were fully removed.

**Comment by SteveKunG** [comment]
Thanks @ROMVoid95 for taking your time to answer this.
Yep, all rockets has been removed. I recommended to play with other addons which has high tier rockets.
